### PR TITLE
Adding global-ss.css

### PR DESCRIPTION
**Pull request by taransamarth**

### CODE REVIEW

**Comment by taransamarth** [comment]
All of the files I added were copied and pasted.

**Comment by lachlanjc** [comment]
Haha, sounds good!

**Comment by taransamarth** [comment]
Hi Lachlan!

**Comment by lachlanjc** [comment]
OK, so what are you working on here?

**Comment by taransamarth** [comment]
Adding the files to GH

**Comment by lachlanjc** [comment]
Sounds good. I think I'll start looking at the JSON file — I'm going to add some response code and a fill in the blank question.

**Comment by taransamarth** [comment]
Can you get on scrollback?

**Comment by lachlanjc** [comment]
Sure, I am now.

**Pull request merged**
