### PR TITLE
Settings Background Feature?

### PR DESCRIPTION
**Pull request by ghost**
I honestly have no idea if this will work for what you want, but I think it should at least do something.

### CODE REVIEW

**Comment by lachlanjc** [comment]
Looks good. I'm going to change it a bit, but this is a good start. Thanks so much Jack!

**Comment by lachlanjc** [comment]
Maybe we should think about this a bit. We don't want our design to clash with some ugly color set by the user… @tns12 what are your thoughts on this?

**Comment by ghost** [comment]
We could just have a few options for them to choose from? Maybe a few colors, then a few pictures. Interested to hear what Taran thinks

**Comment by lachlanjc** [comment]
That’s what I’m thinking. Otherwise it will look awful!

**Comment by taransamarth** [comment]
I think we should have 3 or 4 options for colors. However, this is something that isn't imperative.

**Comment by lachlanjc** [comment]
Definitely. Obviously, white as the default. What about these?
- Light pink
- Light green
- Light blue
- Light orange

**Comment by taransamarth** [comment]
Sure!

## 

---

Taran Samarth
Park Forest Middle School
Timber Rattlers Team
Homebase 552

**Comment by lachlanjc** [comment]
- [ ] Find hex codes for the four theme colors

**Comment by ghost** [comment]
I'm thinking
#FF4500 for orange
#FF6A6A for pink?
#00CDCD for blue
and #00AF33 for green.

**Comment by lachlanjc** [comment]
We need more “pastel” colors. Think about a screen that the entire thing was an incredibly bright orange. That would be kind of nasty! Also, let’s try and find a color “scheme” with Adobe Kuler or something — a consistency between the colors.

**Pull request merged**
