### PR TITLE
Added Clock function

### PR DESCRIPTION
**Pull request by ghost**
The way this would work is you would have a button that changes the value of 'buttonpressed' to 'Start Quiz' and it would trigger the clock.

### CODE REVIEW

**Comment by lachlanjc** [comment]
Awesome! Thanks so much for this.

**Comment by lachlanjc** [comment]
Hmmm...I don't see the clock running. @tns12 Do you see any problems with the JS?

**Comment by ghost** [comment]
I'm not quite done yet, that's just the function, it still needs a display and a timeout. Sorry, working on it right now

**Comment by lachlanjc** [comment]
OK, that’s fine.

**Comment by ghost** [comment]
Can you accept my invite on email chat? I am a bit confused about displaying it.

**Pull request merged**
